// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inputBox': string;
  'tododButton': string;
}
export const cssExports: CssExports;
export default cssExports;
