// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'complited': string;
  'editLink': string;
  'titleEmptyTask': string;
  'todo': string;
  'todoIcon': string;
  'todoListBox': string;
}
export const cssExports: CssExports;
export default cssExports;
